# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\rkagami_worker\"0\n\x12GetProviderRequest\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\"{\n\x13GetProviderResponse\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x12\n\nreplica_id\x18\x02 \x01(\x03\x12\x13\n\x0bupstreamurl\x18\x03 \x01(\t\x12-\n\x06status\x18\x04 \x01(\x0e\x32\x1d.kagami_worker.ProviderStatus\")\n\x0bSyncRequest\x12\x11\n\x04name\x18\x01 \x01(\tH\x00\x88\x01\x01\x42\x07\n\x05_name\"/\n\x0cSyncResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"$\n\x10RegisterResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"\x1e\n\x0bRegisterAck\x12\x0f\n\x07message\x18\x01 \x01(\t\"-\n\x12HealthCheckRequest\x12\x17\n\x0fsupervisor_addr\x18\x01 \x01(\t\"*\n\x13HealthCheckResponse\x12\x13\n\x0bworker_addr\x18\x01 \x01(\t*@\n\x0eProviderStatus\x12\x08\n\x04INIT\x10\x00\x12\x0b\n\x07SYNCING\x10\x01\x12\x0b\n\x07SUCCESS\x10\x02\x12\n\n\x06\x46\x41ILED\x10\x03\x32\xd8\x02\n\x06Worker\x12M\n\x12sync_from_upstream\x12\x1a.kagami_worker.SyncRequest\x1a\x1b.kagami_worker.SyncResponse\x12P\n\x11register_accepted\x12\x1f.kagami_worker.RegisterResponse\x1a\x1a.kagami_worker.RegisterAck\x12U\n\x0chealth_check\x12!.kagami_worker.HealthCheckRequest\x1a\".kagami_worker.HealthCheckResponse\x12V\n\rget_providers\x12!.kagami_worker.GetProviderRequest\x1a\".kagami_worker.GetProviderResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PROVIDERSTATUS']._serialized_start=459
  _globals['_PROVIDERSTATUS']._serialized_end=523
  _globals['_GETPROVIDERREQUEST']._serialized_start=31
  _globals['_GETPROVIDERREQUEST']._serialized_end=79
  _globals['_GETPROVIDERRESPONSE']._serialized_start=81
  _globals['_GETPROVIDERRESPONSE']._serialized_end=204
  _globals['_SYNCREQUEST']._serialized_start=206
  _globals['_SYNCREQUEST']._serialized_end=247
  _globals['_SYNCRESPONSE']._serialized_start=249
  _globals['_SYNCRESPONSE']._serialized_end=296
  _globals['_REGISTERRESPONSE']._serialized_start=298
  _globals['_REGISTERRESPONSE']._serialized_end=334
  _globals['_REGISTERACK']._serialized_start=336
  _globals['_REGISTERACK']._serialized_end=366
  _globals['_HEALTHCHECKREQUEST']._serialized_start=368
  _globals['_HEALTHCHECKREQUEST']._serialized_end=413
  _globals['_HEALTHCHECKRESPONSE']._serialized_start=415
  _globals['_HEALTHCHECKRESPONSE']._serialized_end=457
  _globals['_WORKER']._serialized_start=526
  _globals['_WORKER']._serialized_end=870
# @@protoc_insertion_point(module_scope)
